# Generated by Django 4.2.5 on 2023-09-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_price_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='appName',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='kelas',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
