# Generated by Django 4.2.5 on 2023-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_date_added_product_appname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='appName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='kelas',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
