# Generated by Django 4.2.5 on 2023-09-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_product_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='items',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
