# Generated by Django 4.2.5 on 2023-09-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_items_price_items_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='color',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='items',
            name='size',
            field=models.IntegerField(default=38),
        ),
    ]
