# Generated by Django 4.2.5 on 2023-09-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_items_color_alter_items_price_alter_items_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='color',
            field=models.CharField(max_length=255),
        ),
    ]
