# Generated by Django 4.2.5 on 2023-09-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_items_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='appName',
        ),
    ]
