# Generated by Django 4.2.5 on 2023-09-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_items_appname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='kelas',
        ),
    ]
